<?php
return [
    'default_lang' => 'zh',
    'supported_langs' => ['zh', 'en'],
    'lang_param' => 'lang',
    
    'translations' => [
        'zh' => [
            'site_name' => '邦国崛起官方网站',
            'site_description' => '沉浸式MC国家外交服务器',
            'home_title' => '邦国崛起 · 沉浸式MC国家外交服务器',
            'copy_ip' => '一键复制服务器IP',
            'download' => '客户端懒人包下载',
            'join_qq' => '加入官方QQ群',
            'join_discord' => '加入官方Discord',
            'read_more' => '了解更多',
            'latest_news' => '最新公告',
            'featured' => '精选内容',
            'creator' => '创作者',
            'music' => '音乐专区',
            'video' => '视频专区',
            'worldview' => '世界观',
            'chronicle' => '编年史',
            'nations' => '邦国列表',
            'terms' => '术语库',
            'stories' => '官方剧情',
            'promotion' => '推广素材',
            'faq' => '常见问题',
            'about' => '关于我们',
            'contact' => '联系我们',
            'privacy' => '隐私政策',
            'terms_of_service' => '服务条款',
            'copyright' => '版权声明',
            'submit' => '投稿',
            'search' => '搜索',
            'all' => '全部',
            'official' => '官方',
            'fan_created' => '同人创作',
            'newest' => '最新',
            'popular' => '热门',
            'online_players' => '在线人数',
            'server_uptime' => '开服时长',
            'total_players' => '累计玩家',
            'copied' => '已复制!',
            'copy_failed' => '复制失败',
            'loading' => '加载中...',
            'no_content' => '暂无内容',
            'read_more' => '阅读全文',
            'play_now' => '立即加入',
            'server_ip' => '服务器IP',
        ],
        'en' => [
            'site_name' => 'BangGuo Rise Official Website',
            'site_description' => 'Immersive MC Nation Diplomacy Server',
            'home_title' => 'BangGuo Rise · Immersive MC Nation Diplomacy Server',
            'copy_ip' => 'Copy Server IP',
            'download' => 'Client Download',
            'join_qq' => 'Join Official QQ Group',
            'join_discord' => 'Join Official Discord',
            'read_more' => 'Read More',
            'latest_news' => 'Latest News',
            'featured' => 'Featured',
            'creator' => 'Creators',
            'music' => 'Music',
            'video' => 'Videos',
            'worldview' => 'Worldview',
            'chronicle' => 'Chronicle',
            'nations' => 'Nations',
            'terms' => 'Terms',
            'stories' => 'Stories',
            'promotion' => 'Promotion',
            'faq' => 'FAQ',
            'about' => 'About Us',
            'contact' => 'Contact',
            'privacy' => 'Privacy Policy',
            'terms_of_service' => 'Terms of Service',
            'copyright' => 'Copyright Notice',
            'submit' => 'Submit',
            'search' => 'Search',
            'all' => 'All',
            'official' => 'Official',
            'fan_created' => 'Fan Created',
            'newest' => 'Newest',
            'popular' => 'Popular',
            'online_players' => 'Online Players',
            'server_uptime' => 'Server Uptime',
            'total_players' => 'Total Players',
            'copied' => 'Copied!',
            'copy_failed' => 'Copy failed',
            'loading' => 'Loading...',
            'no_content' => 'No content available',
            'read_more' => 'Read More',
            'play_now' => 'Play Now',
            'server_ip' => 'Server IP',
        ],
    ],
    
    'routes' => [
        'music' => [
            'zh' => '/music',
            'en' => '/music',
        ],
        'video' => [
            'zh' => '/video',
            'en' => '/video',
        ],
        'worldview' => [
            'zh' => '/worldview',
            'en' => '/worldview',
        ],
        'creator' => [
            'zh' => '/creator',
            'en' => '/creator',
        ],
    ],
];
